name: Run Linter

on:
  push:
    paths:
      - '.github/workflows/linting.yml'
      - '**.js'
      - '**.ts'
      - 'package.json'
      - 'package-lock.json'

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Eslint
        run: npm run lint:scripts
