name: run-tests

on:
  push:
    paths:
      - '.github/workflows/run-tests.yml'
      - '**.js'
      - '**.ts'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ["20", "22"]

    name: ${{ matrix.node }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm run test
